### ISSUE TITLE
Where should I put gridmet stuff?

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-python/hytest-evaluation-workflows#4]
@amsnyder I've got some gridmet processing stuff that parker and I worked on.   Preprocessing and exploration notebooks.  
Where should I put them?

**Comment by thodson-usgs** [comment]
`archive/gridmet` is fine for now, I think.

**Comment by amsnyder** [comment]
Yes, agreed with @thodson-usgs - I'm so sorry I must have missed the email when you posted this @rsignell-usgs

**Comment by rsignell-usgs** [comment]
I'm actually thinking I would like to make a new folder in:
https://github.com/USGS-python/hytest-development/tree/main/data-preprocessing
@thodson-usgs, @amsnyder, is that okay with you?

**Comment by amsnyder** [comment]
I would need to have more context to have an opinion. What does Parker's code do? What have you been using the hytest-development repo for? Is it a place to store code that you are still working on and don't want to share in this repo yet?

**Comment by rsignell-usgs** [comment]
I was thinking that creating standardized datasets is an activity more general than evaluation.   Evaluation is just one activity that might use standardized data.

**Comment by amsnyder** [comment]
Sure - I didn't know that the code did, but if it is creating or processing datasets, I think your suggested organization makes sense to me.

**Comment by rsignell-usgs** [comment]
cool, @pnorton-usgs can you please make a folder and contribute your pynco processing scripts?

**Comment by pnorton-usgs** [comment]
I've posted the notebook to hytest-development. I did not realize when I pushed the commit this issue was from the eval repo and does not actually exist in hytest-development. So that commit tries to close a non-existent issue.

**Comment by rsignell-usgs** [comment]
Thanks @pnorton-usgs for https://github.com/USGS-python/hytest-development/commit/4e3ff1e8ca042b10471d743d120343678c836b8a  I'm so glad you could still find it!
